[package]
name = "day4-ipc"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio      = { workspace = true }
tokio-util = { workspace = true }
bytes      = { workspace = true }
nix        = { workspace = true }
serde      = { workspace = true }
bincode    = { workspace = true }
zbus       = { workspace = true }
thiserror  = { workspace = true }
tracing    = { workspace = true }
tracing-subscriber = { workspace = true }

[[example]]
name = "01_uds_server"
path = "examples/01_uds_server.rs"

[[example]]
name = "02_uds_client"
path = "examples/02_uds_client.rs"

[[example]]
name = "03_named_pipe"
path = "examples/03_named_pipe.rs"

[[example]]
name = "04_posix_mq"
path = "examples/04_posix_mq.rs"

[[example]]
name = "05_dbus_intro"
path = "examples/05_dbus_intro.rs"

[[example]]
name = "ex1_tm_bus"
path = "exercises/ex1_tm_bus.rs"

[[example]]
name = "ex1_tm_bus_sol"
path = "exercises/ex1_tm_bus_sol.rs"
