[package]
name = "day7-tctm"
version = "0.1.0"
edition = "2021"

[dependencies]
spacepacket = { path = "spacepacket" }
tokio       = { workspace = true }
tracing     = { workspace = true }
tracing-subscriber = { workspace = true }

[[example]]
name = "01_build_tc"
path = "examples/01_build_tc.rs"

[[example]]
name = "02_parse_tm"
path = "examples/02_parse_tm.rs"

[[example]]
name = "03_route_packets"
path = "examples/03_route_packets.rs"

[[example]]
name = "04_sequence_counter"
path = "examples/04_sequence_counter.rs"

[[example]]
name = "ex1_hk_service"
path = "exercises/ex1_hk_service.rs"

[[example]]
name = "ex1_hk_service_sol"
path = "exercises/ex1_hk_service_sol.rs"
